language: ruby
rvm:
  - 2.3.1
sudo: false
before_script:
  - gem install yamllint
  - pip install --user yamale
  - pip install --user git+https://github.com/PandelisZ/pyyaml.git@allow-emojis
script:
  - yamllint book/_sbpark/*
  - bundle exec ruby -Itest tests/sbPark.rb
  - bundle exec jekyll build
