exclude:
  - .github
  - vendor

collections_dir: book

collections:
  - guestbook
  - sbPark
  - jhKim
  - csNam
  - syChoi
  - goJung
  - whLee
  - jhChoi
  - csSeo
  - jjLee
  - sgKim
  - smJung
  - kyKang
  - khLee
  - jtKang

workshop:
  name: 
  github: https://github.com/PandelisZ/workshop-guestbook
